version: '3.0'

services:
  # SOFTWARE
  pokemon-api-service:
    image: valyo95/microservices/poke-api-service:0.0.1-SNAPSHOT
    expose:
      - 8080
    ports:
      - "${POKEMON_SERVICE_PORT}:8080"
    logging:
      driver: "json-file"
      options:
        max-file: ${LOGGING_MAX_FILE}
        max-size: ${LOGGING_MAX_SIZE}