server:
  port: 8080

pokemon:
  initializeDB: false
  # time interval in ms to clear the pokemon cache in PokeApi Client
  # default value: 600000 ms = 10 minutes
  clearPokemonApiCache: 600000

spring:
  application:
    name: pokemon-service
  datasource:
    driver-class-name: org.h2.Driver
    password: ''
    url: jdbc:h2:mem:pokedb;DB_CLOSE_DELAY=-1
    username: sa
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
#        generate_statistics: true
        jdbc:
          batch_size: 10
        order_inserts: true
    database-platform: org.hibernate.dialect.H2Dialect
#    show-sql: true